version: '3.2'
services:
  adonisv5:
    container_name: "adonisv5"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3333:3333
    volumes:
    - .:/app
    - /app/node_modules

  # Cypress container
  cypress-adonisv5:
    container_name: "cypress-adonisv5"
    build:
      context: ./e2e
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "adonisv5:3333", "--", "cypress run"]
    depends_on:
      - adonisv5
    environment:
      - CYPRESS_baseUrl=http://adonisv5:3333
    volumes:
      - ./e2e:/e2e
